version: '3.6'

services:

  db-master:
    image: "postgres:9.6"
    restart: always
    container_name: "db-master"
    environment:
      POSTGRES_PASSWORD: admin@@090
      db_ENV: dev
    ports:
      - "5433:5432"

  db-slave:
    image: "postgres:9.6"
    restart: always
    container_name: "db-slave"
    environment:
      POSTGRES_PASSWORD: admin@@090
      db_ENV: dev
    ports:
      - "5434:5432"

  db-pgpool:
    build: ./pgpoolv2
    image: "pgpool:v2"
    container_name: "db-pgpool"
    environment:
      db_ENV: dev   
    ports:
      - "5432:9999"
      - "9898:9898"
    depends_on:
        - db-master
        - db-slave
    links:
      - db-master
      - db-slave